# Generated by Django 5.0.4 on 2024-05-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_color_options_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Размер'),
        ),
    ]
