# Generated by Django 5.0.4 on 2024-05-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_stock_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.PositiveSmallIntegerField(verbose_name='Размер'),
        ),
    ]
