# Generated by Django 5.0.4 on 2024-05-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique_for_date='published', verbose_name='Слаг'),
        ),
    ]
