# Generated by Django 5.0.4 on 2024-05-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product', verbose_name='Обувь'),
        ),
    ]
