# Generated by Django 5.0.4 on 2024-05-21 10:50

import django.db.models.deletion
import django.utils.timezone
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_stock_shoe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.cart'),
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.SmallIntegerField(default=products.models.generate_order_number, editable=False, verbose_name='Номер заказа')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(verbose_name='ФИО')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('delivery_type', models.CharField(choices=[('CD', 'CDEK'), ('PO', 'Почта России')], default='PO', max_length=2, verbose_name='Доставка')),
                ('tracking_number', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Трек номер')),
                ('delivery_status', models.CharField(choices=[('FM', 'Сформирован'), ('ST', 'Отправлен'), ('RC', 'Получен')], default='FM', max_length=2, verbose_name='Статус заказа')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to='products.cart')),
            ],
            options={
                'verbose_name': 'Информация о заказе',
                'verbose_name_plural': 'Информация о заказах',
                'ordering': ['-order_date'],
            },
        ),
    ]
