# Generated by Django 5.0.4 on 2024-05-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_cart_options_alter_cartitem_cart_orderinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='cart',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order',
            field=models.JSONField(null=True, verbose_name='Детали заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('WN', 'Зима'), ('SM', 'Лето'), ('AS', 'Весна/Осень')], default='SM', max_length=2, verbose_name='Сезон'),
        ),
    ]
