# Generated by Django 5.0.4 on 2024-05-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_orderinfo_options_orderinfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'ordering': ['-order_date'], 'verbose_name': 'Информация о заказе', 'verbose_name_plural': 'Информация о заказах'},
        ),
    ]
