# Generated by Django 5.0.4 on 2024-05-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_cartitem_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('shoe', 'size')},
        ),
    ]
