# Generated by Django 5.0.4 on 2024-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
