# Generated by Django 5.0.4 on 2024-05-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_orderinfo_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_info', to='products.cart'),
        ),
    ]
