# Generated by Django 5.0.4 on 2024-05-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_discount_end_date_alter_discount_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='name',
            new_name='promocode',
        ),
    ]
