# Generated by Django 5.0.4 on 2024-05-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_name_discount_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='in_archive',
            field=models.BooleanField(null=True, verbose_name='В архиве'),
        ),
    ]
