# Generated by Django 5.0.4 on 2024-05-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_orderinfo_in_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='in_archive',
            field=models.BooleanField(default=False, null=True, verbose_name='В архиве'),
        ),
    ]
